name: main
on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
        with:
          java-version: 8

      - run: npm install
      - run: npm run production-build
      - run: npm run cordova-prepare

      - name: Build
        run: |
          cordova build --buildConfig=/home/runner/work/ui/ui/cordova-build-config.json
          tree ./platforms

      - run: |
          find /home/runner/work/ui/ui/ -name *.apk
      - run: |
          find /home/runner/work/ui/ui/ -name *.AppImage
      - run: |
          find /home/runner/work/ui/ui/ -name *.dmg
      - run: |
          find /home/runner/work/ui/ui/ -name *.msi



      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.STORGANIZER_RELEASE_TOKEN }}
          artifacts: "platforms/electron/build/*AppImage,platforms/android/app/build/outputs/apk/*/*.apk"
