




name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
        with:
          java-version: 8

      - run: npm install
      - run: npm run production-build
      - run: npm run cordova-prepare

      - name: Build
        run: |
          npx cordova -v
          npx cordova build --prod --buildConfig=./cordova-build-config.json

      - run: tree ./platforms
