name: Build Appimage
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:

  build-prepare:
    runs-on: ubuntu-latest
    name: Prepare Build
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: sudo ./build/pipeline/01-container-build-prepare.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prepared-build
          path: |
            ./node_modules/
            ./www/

  build-dev:
    needs: [build-prepare]
    runs-on: ubuntu-latest
    name: Build Dev
    steps:
      - uses: actions/checkout@v3
      - name: Download prepared build
        uses: actions/download-artifact@v4
        with:
          name: prepared-build
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
      - run: sudo ./build/pipeline/02-container-build-appimage.sh --github
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-dev
          path: |
            ./platforms/electron/build/

  build-release:
    needs: [build-prepare]
    runs-on: ubuntu-latest
    name: Build Release
    steps:
      - uses: actions/checkout@v3
      - name: Download prepared build
        uses: actions/download-artifact@v4
        with:
          name: prepared-build
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
      - run: sudo ./build/pipeline/02-container-build-appimage.sh --github --release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-release
          path: |
            ./platforms/electron/build/


  build-android-dev:
    needs: [build-prepare]
    runs-on: ubuntu-latest
    name: Build Android Dev
    steps:
      - uses: actions/checkout@v3
      - name: Download prepared build
        uses: actions/download-artifact@v4
        with:
          name: prepared-build
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
      - run: sudo ./build/pipeline/02-container-build-android.sh --github
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-dev-android
          path: |
            ./platforms/android/app/build/




  release:
    needs: [build-dev, build-release, build-android-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Download dev build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-dev
      - name: Download release build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-release
      - name: Download android dev build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-dev-android
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.STORGANIZER_RELEASE_TOKEN }}
          artifacts: "*AppImage,*apk"
