name: main

on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: coturiv/setup-ionic@v1
        with:
          java-version: 8

      - run: npm install
      - run: npm run production-build
      - run: npm run cordova-prepare

      - name: Build
        run: |
          cordova -v
          cordova build --prod --buildConfig=/home/runner/work/ui/ui/cordova-build-config.json

      - run: |
          echo "ARTIFACT_APK=$(find /home/runner/work/ui/ui/ -name *.apk)" >> "$GITHUB_ENV"
      - run: |
          echo "ARTIFACT_APPIMAGE=$(find /home/runner/work/ui/ui/ -name *.AppImage)" >> "$GITHUB_ENV"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*AppImage,*.apk"
