




name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:


      - uses: bahmutov/npm-install@v1

      - run: npm i
      - run: npm run production-build
      - run: npm run cordova-prepare


      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          java-version: 8
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8



      - name: Build
        run: |
          ionic cordova build electron --prod
