name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm i
      - run: npm run production-build
      - run: npm run cordova-build electron